### ISSUE TITLE
Emmet HTML expansion not working

### ISSUE THREAD

**Issue by ourcore** [Digitalbrainstem/ejs-grammar#10]
In VS Code 1.20.1, the Emmet HTML expansion functionality (i.e., `div.foo>ul#bar`) doesn't work when the language mode is set to "JavaScript EJS" in .html files. I also confirmed that the expansion still works on .html files using HTML as the language mode.

**Comment by Betanu701** [comment]
For this to work, I have to write the language server. Unfortunately, there is not a setting I can turn on, at least not one that I have found, that will allow me to do this. I tried to use HTML or Javascript language server as a bases, but that ended up being much more of a pain.

I am working on the language server portion though. Hang tight.

**Comment by ourcore** [comment]
@Betanu701 I see. Thanks for the explanation. Looking forward to this! And thank you for keeping the extension alive and updated!

**Comment by Ricka7x** [comment]
@ourcore try this...

"emmet.includeLanguages": {
    "ejs": "html"
  },

**Comment by w-biggs** [comment]
> "emmet.includeLanguages": {
> "ejs": "html"
> },

This seems to have made the EJS autocomplete no longer work, although syntax highlighting still works. Changing the `"html"` to some combination of `["html", "javascript", "ejs"]` doesn't seem to work either.

**Comment by Betanu701** [comment]
Using html as base now. 

Set file.association for "*.ejs" to "html"
