### ISSUE TITLE
don't highlight with "<?php" (php open tag)

### ISSUE THREAD

**Issue by gulping** [Digitalbrainstem/ejs-grammar#12]
I'm using EJS for generate PHP.

```ejs
<?php
some php
<%= some ejs -%>
?>
<%= some ejs -%>
<div>some html</div>
```

"<?" is regarded as EJS open tag and whole PHP code is highlighted as JS.
please consider that ignore "<?php".

**Comment by Betanu701** [comment]
Going to publish a beta version. Please test this. If it works and you don't see problems, I will push it to master.

**Comment by Betanu701** [comment]
Please see the branch "exclude-php". It does mess up the highlighting for php unless you have another extension that basically does what this extension does but for php.

**Comment by Betanu701** [comment]
This is included in the main branch.
