### ISSUE TITLE
`scripts` entry in package.json

### ISSUE THREAD

**Issue by meesfrensel** [Digitalbrainstem/ejs-grammar#13]
There is an entry in `scripts` in package.json:
```json
"scripts": {
    "update-grammar": "node ../../build/npm/update-grammar.js grammars/ejs.json ./syntaxes/ejs.json"
}
```
However, `update-grammar` is not a standard script, at least it's not listed in the [official docs](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_fields) (which list [one script](https://code.visualstudio.com/docs/extensions/publish-extension#_prepublish-step), and point to the [npm docs](https://docs.npmjs.com/misc/scripts) for other standard npm scripts, where it's also not listed). I therefore think it should be removed entirely. Of course, unless there is a purpose that I can't find!

**Comment by ExE-Boss** [comment]
This is run using `npm run update-grammar`.

As for its purpose, the author of this package uses it to update the&nbsp;`ejs.json` TextMate language&nbsp;definition.
