### ISSUE TITLE
ejs in template literal support

### ISSUE THREAD

**Issue by S2-** [Digitalbrainstem/ejs-grammar#17]
I often use js template literals to store the ejs templates, like this
```
var template = `
<div>
  <p><%= name %></p>
</div>
`;
 ```

and then render the template with `element.innerHTML(ejs.render(template, {name: "Simon"}));`

Only problem is the template string is not syntax highlighted.
Would it be possible to add this feature somehow like [lit-html](https://github.com/mjbvz/vscode-lit-html) does?

**Comment by Betanu701** [comment]
Can you verify this with version >1.0.0. It may have been fixed.

**Comment by S2-** [comment]
Hi @Betanu701, I'm not using template literals anymore. I switched to single template files with `ejs-render-remote`.

**Comment by Betanu701** [comment]
literals have been added in version 1.1.4 (release 1.2)
