### ISSUE TITLE
Some autocomplete tags does not show up after installing plugin

### ISSUE THREAD

**Issue by AbrahamLara** [Digitalbrainstem/ejs-grammar#18]
# Before installing
<img width="739" alt="screen shot 2018-06-12 at 11 20 50 am" src="https://user-images.githubusercontent.com/37315075/41300035-c847d3b4-6e32-11e8-8f12-fa0e002869fa.png">

# After installing
<img width="709" alt="screen shot 2018-06-12 at 11 18 16 am" src="https://user-images.githubusercontent.com/37315075/41299897-7cb5cdd4-6e32-11e8-8a75-99c9a5c8e201.png">

Hope this gets fixed 👍 Thanks!!

**Comment by Betanu701** [comment]
Until we get time to bake this in, requires some significant coding, as of right now, we would have to duplicate what is in html and javascript to get it to work properly. We do not really want to do this, we are working on getting a langauge server built that we can pull in html and javascript. For now though, there is a good snippet plugin that works decently for what you are asking.

It is called "ejs Snippets" by TaodongWu

That should at least get you to where you need for right now. Let me know if you need any help.
