### ISSUE TITLE
Document Formatter

### ISSUE THREAD

**Issue by Skarvion** [Digitalbrainstem/ejs-grammar#19]
It doesn't seem that this plugin can format document yet, as in auto-indent and clean up whitespaces in code yet. I don't know if this feature already implemented or not as it gives out an error message. I think it will be a neat feature.

![image](https://user-images.githubusercontent.com/17715991/42915806-62a7f680-8b45-11e8-8b66-cd28c46fd2b7.png)

**Comment by Nikita-schetko** [comment]
Guys, any plans to add formatter for 'ejs' files ?

**Comment by Betanu701** [comment]
Updated version. Use >1.0.0. Using html as base language.
