### ISSUE TITLE
Snippet Support

### ISSUE THREAD

**Issue by Betanu701** [Digitalbrainstem/ejs-grammar#2]
Need to add Snippet support so others using the language can have code completion for the EJS part.

**Comment by meesfrensel** [comment]
Hi, since it's been 3 months I'm guessing you're not working on this (anymore). I would like to add snippet support! Where can I find useful snippets to include? Or is there no such resource, and does everything have to be thought of from scratch?

**Comment by Betanu701** [comment]
@meesfrensel 

Yes it has been several months, I am not dead! just been crazy busy with my ft job. Have not had much time in the past couple months to add to this. I see you have a pull request into me to update some things. Let me check it out tonight. I glanced at it briefly, but have not dug looked at it. If I think that it is good and done well, Would you like to be put on as a contributor to this? 

As for the snippets, the only resources that I have would be ejs.co. There was another library that was written for ejs snippets. I do not think it has been active. We may be able to reach out to them and see if they mind us taking the code and integrating it into this library. [ejs snippets](https://github.com/abusaidm/html-snippets)

 Let me know what you think.

**Comment by Betanu701** [comment]
My goal would be to pull in not only ejs snippets but use html and JavaScript snippets as well. I do not want to have to re-invent the wheel as we already have html and JavaScript language in their own files. I believe with the language server we can link to the other extensions and use the snippets libraries they already have.  I have not had time to delve into this yet. If you want to try to figure this out, be my guest! I would love to learn, if you do figure it out.

**Comment by meesfrensel** [comment]
Good to hear you aren't dead because this extension has a lot of potential :)
> Would you like to be put on as a contributor to this?

Sure, sounds good!

On snippets: I think you can easily 'include' html/js snippets but it's much more difficult to show the right snippet in the right scenario (e.g. no html snippets within an ejs block). I'll definitely look into the language server as it sounds very useful, though I can't promise anything!

**Comment by Betanu701** [comment]
@meesfrensel

When ever you want me to push code live, I can push dev to a beta branch on vscode, just let me know. If you think it is ready for prod, create a pull request to master, and I will test it and push it to vscode master.

**Comment by ExE-Boss** [comment]
The JavaScript snippets work with #33.

**Comment by Betanu701** [comment]
Snippets have been added in version 1.2
