### ISSUE TITLE
Installing extension kills autocomplete/auto-indent

### ISSUE THREAD

**Issue by Benji-Leboe** [Digitalbrainstem/ejs-grammar#21]
After installing EJS language support auto-compete of closing tags and auto-indent stopped working.

Really annoying. Shouldn't affect VSCode like this. Please fix it

Edit: upon further research can re-associate .ejs with HTML by adding the following to VSCode/preferences/settings, but this kills the highlighting of ejs syntax.

Is there a way to keep HTML formatting but ejs syntax highlighting?

```
{
    "files.associations": {
        "*.ejs": "html"
    },
}
```

**Comment by ExE-Boss** [comment]
The tag auto&#x2011;closing can be fixed by&nbsp;installing the&nbsp;[Auto&nbsp;Complete&nbsp;Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-complete-tag) extension.

**Comment by fferreira12** [comment]
It would be really great to have both the EJS language support and the HTML auto-complete feature.
Any news on that?

**Comment by Betanu701** [comment]
Updated to use html as base. Use version >1.0.0
