### ISSUE TITLE
Wrong syntax highlight when using @ in css

### ISSUE THREAD

**Issue by pepjo** [Digitalbrainstem/ejs-grammar#27]
When using @ in the css like in the following screenshot:
![screenshot_2019-03-08_10-23-17](https://user-images.githubusercontent.com/1307305/54023312-88ed7100-418c-11e9-86ab-e80e485060bb.png)
the syntax highlight gets messed up in the rest of the document:
![screenshot_2019-03-08_10-22-38](https://user-images.githubusercontent.com/1307305/54023330-9d316e00-418c-11e9-9ed0-1ba5645cd20a.png)

**Comment by Betanu701** [comment]
Thank you for posting this. I do remember seeing something similar to this in the past. I was just doing some testing on my own code that is similar to what you posted, I noticed that unless you place some type of ending tag it will mess up all following highlighting. Just out of curiosity on line 29, can you place a ';' after ocLogo?

Also, more of reviewing your code, not related to this, why are you mixing string html with ejs? You can build the function with all function parts inside ejs tags and have the html stand by itself outside ejs tags.  If there is a reason you chose this way, I am genuinely curious as to why you this way is better in your mind. I could very well be wrong in my thinking. I love to learn other and different ways.

**Comment by Betanu701** [comment]
I will make this a separate issue, but when I "commented out" a single line with double slashes with an ending ejs tag on the same line, this also caused errors.

**Comment by ExE-Boss** [comment]
I think it’s partly because of&nbsp;line&nbsp;19, where you’re using EJS inside CSS, which is&nbsp;untested and probably doesn’t work.

In either case, you really should avoid using inline `<style>` blocks.

**Comment by ExE-Boss** [comment]
Also, can you upload the file so that I can inspect this on my end.

**Comment by ExE-Boss** [comment]
This seems to have simply disappeared with the fix for #31.

Also, I couldn’t reproduce this with the latest stable release.

**Comment by pepjo** [comment]
> Also, can you upload the file so that I can inspect this on my end.

Sorry, I did not see the comment. Good thing it got solved, thank you!
