### ISSUE TITLE
Surrounding passed variable in quotes causes the rest of the file to be seen as a string

### ISSUE THREAD

**Issue by Fudge0952** [Digitalbrainstem/ejs-grammar#31]
Simply put, when I'm reading a passed variable in my ejs code I have a `<script>` snippet which dumps the value of the passed variable into a javascript variable. The code works fine and runs however all the code after the first quote is seen as a string (see attached screenshot below for example).

This is with the passed variable
![image](https://user-images.githubusercontent.com/3098078/54501728-201bab00-497b-11e9-9a2d-d5aa0c65d210.png)

This is without
![image](https://user-images.githubusercontent.com/3098078/54501746-3fb2d380-497b-11e9-81a9-8371111f9559.png)

I assume this is not the expected output?

**Comment by ExE-Boss** [comment]
Again, EJS embedded inside `<script>` or&nbsp;`<style>` is&nbsp;untested and broken as&nbsp;they have weird behaviour.
