### ISSUE TITLE
Closing tags colors are broken after multi-line operator

### ISSUE THREAD

**Issue by greenroach** [Digitalbrainstem/ejs-grammar#39]
![image](https://user-images.githubusercontent.com/6224866/63639087-5ed72f00-c698-11e9-904f-bdece67559b2.png)

## Steps to reproduce:

```ejs
<header>
    <div>
        <% for(item of items) { %>
            test
        <% } %>
    </div>
</header>
```

## Expected result:
Closing tag should be the same color as opening

**Comment by Betanu701** [comment]
Yup! That was a bug. It should be fixed now with the latest. version 1.1.2
