### ISSUE TITLE
Highlighting not recognizing closing EJS comment

### ISSUE THREAD

**Issue by illz** [Digitalbrainstem/ejs-grammar#42]
## Steps to reproduce:
As of the August 26 2019 update, when you have a multi-line EJS comment the syntax highlighting is not recognizing the end of the comment and thus coloring the remainder of the file as a comment.
Example code and linked screenshot below:

```ejs
<% /* %>
All this fine HTML should be commented out, as well as <%= 'any embedded controls and output' %>
<% for (let i = 0; i < 5; i++) { %>
Hi there!
<% } %>
<% */ %>
This text below the closing comment should return to normal syntax highlighting as it is no longer commented out.
```

Here is a screenshot showing the current behavior - note the bottom closing comment is syntax highlighted red, yet everything below it to the end of the file remains colored as a comment.
<img width="555" alt="Screenshot 2019-08-29 12 01 37" src="https://user-images.githubusercontent.com/7015979/63968505-c6083100-ca54-11e9-9310-abb49ce18953.png">

**Comment by Betanu701** [comment]
This should be fixed

@illz Can you confirm this has been fixed in version 1.2.0?

**Comment by illz** [comment]
<img width="352" alt="Screenshot 2020-01-14 10 57 23" src="https://user-images.githubusercontent.com/7015979/72373229-b7957b80-36bc-11ea-84ae-4681d858f091.png">
It is definitely improved in that it doesn't mark the rest of the file as a comment, but if you use the correct syntax which closes the tag after the comment start and uses another open+close tag to wrap the comment end, nothing in between gets lowlighted as commented out.
Correct EJS comment syntax should be:
`<% /* %> commented-out code <% */ %>`

**Comment by Betanu701** [comment]
@illz Are you positive this is how it should work? Basically this creates a block comment for an entire section of html and javascript. To me this does not make sense as ejs requires the scriptlet tags to function.  so once you close the scriptlet tag it no longer runs ejs. Basically this would mean that '/*' takes precedence which would negate the ending '%>' tag. This could be the case here. 

If I am wrong, I think I can get this working. But I would say the correct usage would be
```
<% /* 
Some code including html
*/ %> 
```

**Comment by Betanu701** [comment]
@illz Ok, I did verify the functionality. I have a fix for this. Can you test my local branch to see if it works correctly before I push it live?

[branch](https://github.com/Digitalbrainstem/ejs-grammar/tree/EJS-Comment-Block)

**Comment by illz** [comment]
<img width="490" alt="Screenshot 2020-01-14 14 02 21" src="https://user-images.githubusercontent.com/7015979/72386624-93df2f00-36d6-11ea-9fd2-bfebd97e0eb0.png">
Looks great! Thanks for being responsive on this issue. Yes, for multi-line block comments you need to close the tag after the comment start and have a separate open+close for the comment end. Strange but ... such is life ;)

**Comment by Betanu701** [comment]
Ok, This has been published, should be able to update in just a few mins.
