### ISSUE TITLE
Trying to use slots with template tag in an inline template breaks syntax highlighting

### ISSUE THREAD

**Issue by kyletheninja** [Digitalbrainstem/ejs-grammar#45]
The problem in a nutshell is this, using my dropdown component  example:
```javascript
Vue.component('test', {
  template : `
  <dropdown label='My Button contents'>
    <my-actual-menu-component></my-actual-menu-component>
  </dropdown>
  `,
   beforeCreate() {
      console.log('whatever');
    }
})
```

Above everything is highlighted correctly, but as soon as I use the template tag in there like so:

```javascript
Vue.component('test', {
  template : `
  <dropdown>
    <template #btn>
      My Button Contents<i class='icon></i>
    </template>
    <my-actual-menu-component></my-actual-menu-component>
  </dropdown>
  `,
   beforeCreate() {
      console.log('whatever');
    }
})
```

The template string and everything above it is highlighted properly, but everything after the backtick enclosed string gets highlighted as if it is a string. If I remove the ` #btn` from the `<template #btn>` tag so that there are no spaces between `template` and its opening and closing angle brackets, only the template tags themselves get highlighted as strings, and the rest of the document is fine. However, in order to use slots properly we must necessarily use the name sometimes, as in this case where the default slot is already being used for the dropdown menu, not the toggle button. I should mention that `<template v-slot:btn>` does not work either. It seems to be the space, even `<template >` gives the same bug.

For now my workaround is to put the template at the bottom of the definition object, since it only messes with the highlighting after it. Thank you for this plugin by the way! This is the best way to write components, I've wanted it since I started using angularjs 5 years ago.

**Comment by kyletheninja** [comment]
I think I posted this in the wrong place, dunno how I got here.

**Comment by Betanu701** [comment]
I believe this is for my Javascript-Vue extension.

**Comment by Betanu701** [comment]
Closing this as it pertains to another extension.

**Comment by Betanu701** [comment]
Moved to [Javascript-Vue #4](https://github.com/Digitalbrainstem/Javascript-Vue/issues/4)
