### ISSUE TITLE
Comments get escaped on ending %>

### ISSUE THREAD

**Issue by Betanu701** [Digitalbrainstem/ejs-grammar#5]
Comments with nested tags are being escaped by nested %>.

**Comment by ExE-Boss** [comment]
Can you provide me an example snippet so that I can debug this?

**Comment by Betanu701** [comment]
```
<%# This a block level comment
  <% some code that should be commented out %>
%> 
```

**Comment by Betanu701** [comment]
![image](https://user-images.githubusercontent.com/5798012/52379114-7d951180-2a37-11e9-80e2-6a5aa48e7857.png)

@ExE-Boss To show you what it does in the editor

**Comment by Betanu701** [comment]
This could be seen multiple ways. According to the specs I should be doing line by line ending each line with %>. I see it as a bug though because it technically still runs so we should support anything that "runs".

**Comment by ExE-Boss** [comment]
Technically, that’s correct, as you can’t nest EJS tags inside EJS comments (if you do, EJS throws an error):

```ejs
<%#
  <% invalid %>
%>
```

**Comment by Betanu701** [comment]
I am ok with that! I will go ahead and close this.

**Comment by ExE-Boss** [comment]
You should also probably mark this issue with [the&nbsp;**invalid**&nbsp;label](https://github.com/Digitalbrainstem/ejs-grammar/labels/invalid).
