### ISSUE TITLE
IF statement problem.

### ISSUE THREAD

**Issue by honeymaro** [Digitalbrainstem/ejs-grammar#7]
<% if(filename.startsWith("market")){ %>
		<style>
			header {}
		</style>
	<% } %>

When I write code like this, 

Coloring problem is exist.

**Comment by honeymaro** [comment]
![image](https://user-images.githubusercontent.com/8274951/36360886-0aef6ef0-156b-11e8-8a4a-b545e41970c7.png)

**Comment by Betanu701** [comment]
I am not seeing this issue.

Check to make sure you have Javascript EJS not .ejs installed. This issue is present in the old .ejs language grammar.

Also make sure you have Javascript EJS enabled. 
![ejs_issue](https://user-images.githubusercontent.com/5798012/36709260-f46bb8e8-1b44-11e8-8832-27bac63cc421.PNG)

**Comment by xsorifc28** [comment]
This problem happens for me as well. If I close the ejs tag without closing a bracket, highlighting breaks - exact problem as in the image from the reporter. 

Javascript EJS is enabled, version 0.2.3.

**Comment by Betanu701** [comment]
Can you open a new window and create a new ejs file and paste the code that is above and post a full screen, screen shot?

**Comment by xsorifc28** [comment]
Download the images & flip through to see it better. The difference is that when I close the bracket in the `<% %>` tag, it works fine. However, If I don't close the bracket and close it much later in the code with a different `<% %>` tag, it doesn't work.

Incorrect highlighting:
![screen shot 2018-03-12 at 12 01 44 pm](https://user-images.githubusercontent.com/5721836/37294899-464447fe-25ed-11e8-9598-fb3daaa60dd1.png)

Correct highlighting:
![screen shot 2018-03-12 at 12 02 08 pm](https://user-images.githubusercontent.com/5721836/37294900-465577e0-25ed-11e8-88cc-67cdec26907f.png)

**Comment by Betanu701** [comment]
I will need to look into this to get it working. I can see what you mean now. As a work around, If you enclose each line with <% %>, that should work.

I also found another error in my usage. For some reason if you have @media, the @ symbol is causing the system to wig out. 

I will try to get this fixed as soon as I can.

Thanks
