### ISSUE TITLE
After autocompletion there is a space after the ejs syntax.

### ISSUE THREAD

**Issue by Fernando-Lozano** [Digitalbrainstem/ejs-grammar#74]
Is there a way to get rid of the extra space?

```ejs
<li><%= %> </li>
```

## Expected result:
```ejs
<li><%= %></li>
```

**Comment by beeburrt** [comment]
Was there ever a solution to this?

I love this extension but that extra space is annoying.

**Comment by Fernando-Lozano** [comment]
If I recall correctly. A workaround that I did was edit the extension directly by finding the snippets.json file and, as an example, I changed the EJS No Output body from “ <% $1 %> $2” to “ <% $1 %>$2”.

**Comment by Betanu701** [comment]
New version was just published. I am waiting for it to authenticate then it should be available in extensions.
 
Thanks for your help!

**Comment by Betanu701** [comment]
Ok New version is available!
