### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by UsiTheStorm** [Digitalbrainstem/ejs-grammar#88]
Ejs code don't become grey while commented out.

![image](https://user-images.githubusercontent.com/50480382/184163084-ee684c53-5a86-4995-9d16-06422536dacf.png)

**Comment by Betanu701** [comment]
I am not near a computer to test it. Are you sure the actual JS code is
commented out. I know you commented the html out, just not sure the actual
ejs code is commented out.

**Comment by UsiTheStorm** [comment]
Oh. Got it. Need to comment out EJS code with `<%#` tag
