### ISSUE TITLE
last vscode update broke things?

### ISSUE THREAD

**Issue by skywalk1411** [Digitalbrainstem/ejs-grammar#92]
## Steps to reproduce:

All opening <% {%> or <%}%> tags are now red colored as if there is an error?

<table><td>
📝 <strong>Note:</strong> Remember to link to a repository or upload a code snippet that reproduces the issue as an attachment (or a code block if it’s short) to this issue: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
</td></table>

```ejs
<%# short code snippet that reproduces the issue goes here %>
```

**Comment by ecmel** [comment]
Fixed in the latest VS Code release.

**Comment by skywalk1411** [comment]
> Fixed in the latest VS Code release.

Also I am not certain, but if I make a button with a onclick="theFunction(parameter1,parameter2)" and replace the parameters 1 or 2 with a ejs entry, its flagged as an error, but its valid ejs code.

**Comment by skywalk1411** [comment]
sorry for my "shitty" code but here example:

https://imgur.com/Xrdg6ef

`<% if (post.nsfw === true) {%><div class="form-check form-switch sticky-top float-end">
            <input class="form-check-input text-bg-secondary border border-secondary-subtle bg-secondary-subtle" id="nsfw<%=post.id%>" type="checkbox" role="switch" value="yes" id="switchPost<%=post.id%>" onclick="nsfw(<%=post.id%>,<%if (isStringParsedArray(post.images)) {%><%=post.images%><%} else {%>null<%}%>)" checked>
            <label class="form-check-label" for="switchPost<%=post.id%>">nsfw</label>
          </div><%}%>`
