### ISSUE TITLE
Source code for latest release

### ISSUE THREAD

**Issue by trymeouteh** [Digitalbrainstem/ejs-grammar#97]
The latest version on Visual Studio Marketplace is 1.3.3
https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support

However the latest version in this git repo is 1.2.1

Please release the source code as it is licensed under MIT

**Comment by Betanu701** [comment]
All code on the repo is the latest code. I don't see where you are getting 1.2.1. I do see 1.3.1 in the package file, I probably forgot to update that when I pushed in several years ago. All code here matches what is in the marketplace.

**Comment by trymeouteh** [comment]
I did not see a 1.3.1 tag and therefore did not know that the code was updated since then
